### PR TITLE
add: question & result page

### PR DESCRIPTION
**Pull request by nayyyhaa**
Added question & result page for quiz app.

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
UI & code both look good. Nice work 💯 

Appreciation - Liked the UI and semantic html used consistently.

**Comment by nayyyhaa** [comment]
> UI & code both look good. Nice work 💯
> 
> Appreciation - Liked the UI and semantic html used consistently.

Thankyou @anik31 :)

**Review by keshavkumar-in — APPROVED** [review]
Nice UI, looks good to me. You can merge it.

**Comment by nayyyhaa** [comment]
> Nice UI, looks good to me. You can merge it.

Thanks @keshavkumar-in :)

**Comment by nayyyhaa** [comment]
Merging the PR.

**Pull request merged**
